### ISSUE TITLE
[mild spoiler] Glyph masks/parts confusing, glyph hover popup lists duplicate parts

### ISSUE THREAD

**Issue by ZephyrCloudrunner** [madidier/tunic-helper#1]
I don't entirely understand how to use the masks correctly, so I'm possibly setting them up incorrectly, but even so this feels like probably a bug:
![image](https://github.com/madidier/tunic-helper/assets/1295880/0dd14fa7-ec21-4da3-b263-66fd523c808e)

I did try looking into the code but I'm not very experienced and I don't know really what I'm doing or how to see what the code is doing while it's running. As some context, the way I've set up the glyph parts is each sound is a separate entry with letters representing it, and I can use the `: characters to type with those just fine. The masks I've set up the same as the parts, except without the definitions (since they don't have them). Am I doing this incorrectly?

Absolutely amazing tool over all, though. It's been incredibly helpful on my journey into making sense of this language.

**Comment by madidier** [comment]
Thanks a lot for your feedback !

As a rule of thumb, your masks should not overlap. You are getting the same part recognized several times because it matches more than one mask.

I have updated the "Advanced Tunic-Helper" [Gist](https://gist.github.com/madidier/d39adaddc80eeb54925c1c19d09234e7) with some explanations about masks. Let me know if that clears things up or if it needs improvement :)

**Comment by ZephyrCloudrunner** [comment]
This does help, and I think I figured out how they work well enough for my purposes. I still find the concept a bit confusing, but I largely blame that on my own inexperience rather than the description. I've managed to figure out how best to set it up, though, which is what I needed. Thank you!
